#!/bin/bash

echo "Warning: this script bulk renames files."
echo -n "Continue? (y/n) "
read answer

Rename() {
	for name in test-*
	do
		newname="parse-$(echo $name | cut -c 6-)"
		mv $name $newname
	done
}

if echo "$answer" | grep -iq "^y"; then
	Rename
fi


