#!/bin/sh
# vim: filetype=sh

# ================================== #
# Testing Script for Stop
# ================================== #

# Step through a list of files
# Compile, run, and check output of each expected-to-work test
# Compile and check the error of each expected-to-fail test

STOP="./stop.native"
TEST_FOLDER="tests"

ulimit -t 30

${STOP} ${TEST_FOLDER}/test-$1.stp
