#!/bin/bash
# vim: filetype=sh

# =============================== #
# Testing Script for Parser Tests
# =============================== #

STOP="./stop.native"
PROGNAME=$(basename $0)
TEST_FOLDER="tests"

# Set time limit for all operations
ulimit -t 30

globalerror=0

error_exit() {
	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
	echo "($ ./test -h for help)"
	exit $globalerror
}

# Usage informaition
Usage() {
	echo "Usage: test [filename]"
	echo "[filename] is <name> in ${TEST_FOLDER}/parse-<name>.stp"
	echo "e.g. Running ${TEST_FOLDER}/parse-comments1.stp:"
	echo "$ ./test comments1"
	exit 1
}

# Handle -options
while getopts ":h[help]" opt; do
	case $opt in
		h) # Help
			Usage
			;;
	esac
done

if [ ! -f ${TEST_FOLDER}/parse-$1.stp ]; then
	globalerror=1
	error_exit "${TEST_FOLDER}/parse-$1.stp not found"
fi

if [ ! -f /$(basename $STOP) ]; then
	globalerror=1
	error_exit "Missing $(basename $STOP) executable. Try building project."
fi

$STOP -a < ${TEST_FOLDER}/parse-$1.stp
