// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/Analysis/Verifier.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/IRPrintingPasses.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/LegacyPassManager.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>
#include <algorithm>
using namespace llvm;

Module* makeLLVMModule();

int main(int argc, char**argv) {
  Module* Mod = makeLLVMModule();
  verifyModule(*Mod, PrintMessageAction);
  PassManager PM;
  PM.add(createPrintModulePass(&outs()));
  PM.run(*Mod);
  return 0;
}


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("tmp.bc", getGlobalContext());
 mod->setDataLayout("");
 mod->setTargetTriple("x86_64-pc-linux-gnu");
 
 // Type Definitions
 ArrayType* ArrayTy_0 = ArrayType::get(IntegerType::get(mod->getContext(), 8), 14);
 
 PointerType* PointerTy_1 = PointerType::get(ArrayTy_0, 0);
 
 std::vector<Type*>FuncTy_2_args;
 FuncTy_2_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_2 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_2_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_3 = PointerType::get(IntegerType::get(mod->getContext(), 32), 0);
 
 std::vector<Type*>FuncTy_4_args;
 FunctionType* FuncTy_4 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_4_args,
  /*isVarArg=*/false);
 
 StructType *StructTy_class_anon = mod->getTypeByName("class.anon");
 if (!StructTy_class_anon) {
 StructTy_class_anon = StructType::create(mod->getContext(), "class.anon");
 }
 std::vector<Type*>StructTy_class_anon_fields;
 StructTy_class_anon_fields.push_back(IntegerType::get(mod->getContext(), 32));
 if (StructTy_class_anon->isOpaque()) {
 StructTy_class_anon->setBody(StructTy_class_anon_fields, /*isPacked=*/false);
 }
 
 PointerType* PointerTy_5 = PointerType::get(StructTy_class_anon, 0);
 
 PointerType* PointerTy_6 = PointerType::get(FuncTy_2, 0);
 
 std::vector<Type*>FuncTy_8_args;
 FuncTy_8_args.push_back(PointerTy_5);
 FuncTy_8_args.push_back(IntegerType::get(mod->getContext(), 32));
 FunctionType* FuncTy_8 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_8_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_7 = PointerType::get(FuncTy_8, 0);
 
 PointerType* PointerTy_9 = PointerType::get(IntegerType::get(mod->getContext(), 8), 0);
 
 std::vector<Type*>FuncTy_11_args;
 FuncTy_11_args.push_back(PointerTy_9);
 FunctionType* FuncTy_11 = FunctionType::get(
  /*Result=*/IntegerType::get(mod->getContext(), 32),
  /*Params=*/FuncTy_11_args,
  /*isVarArg=*/true);
 
 PointerType* PointerTy_10 = PointerType::get(FuncTy_11, 0);
 
 PointerType* PointerTy_12 = PointerType::get(PointerTy_5, 0);
 
 
 // Function Declarations
 
 Function* func__Z13some_functioni = mod->getFunction("_Z13some_functioni");
 if (!func__Z13some_functioni) {
 func__Z13some_functioni = Function::Create(
  /*Type=*/FuncTy_2,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"_Z13some_functioni", mod); 
 func__Z13some_functioni->setCallingConv(CallingConv::C);
 }
 AttributeSet func__Z13some_functioni_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func__Z13some_functioni_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func__Z13some_functioni->setAttributes(func__Z13some_functioni_PAL);
 
 Function* func_main = mod->getFunction("main");
 if (!func_main) {
 func_main = Function::Create(
  /*Type=*/FuncTy_4,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"main", mod); 
 func_main->setCallingConv(CallingConv::C);
 }
 AttributeSet func_main_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_main_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_main->setAttributes(func_main_PAL);
 
 Function* func__ZZ4mainENK3__0clEi = mod->getFunction("_ZZ4mainENK3$_0clEi");
 if (!func__ZZ4mainENK3__0clEi) {
 func__ZZ4mainENK3__0clEi = Function::Create(
  /*Type=*/FuncTy_8,
  /*Linkage=*/GlobalValue::InternalLinkage,
  /*Name=*/"_ZZ4mainENK3$_0clEi", mod); 
 func__ZZ4mainENK3__0clEi->setCallingConv(CallingConv::C);
 func__ZZ4mainENK3__0clEi->setAlignment(2);
 }
 AttributeSet func__ZZ4mainENK3__0clEi_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    B.addAttribute(Attribute::NoUnwind);
    B.addAttribute(Attribute::InlineHint);
    B.addAttribute(Attribute::UWTable);
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func__ZZ4mainENK3__0clEi_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func__ZZ4mainENK3__0clEi->setAttributes(func__ZZ4mainENK3__0clEi_PAL);
 
 Function* func_printf = mod->getFunction("printf");
 if (!func_printf) {
 func_printf = Function::Create(
  /*Type=*/FuncTy_11,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"printf", mod); // (external, no body)
 func_printf->setCallingConv(CallingConv::C);
 }
 AttributeSet func_printf_PAL;
 {
  SmallVector<AttributeSet, 4> Attrs;
  AttributeSet PAS;
   {
    AttrBuilder B;
    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
   }
  
  Attrs.push_back(PAS);
  func_printf_PAL = AttributeSet::get(mod->getContext(), Attrs);
  
 }
 func_printf->setAttributes(func_printf_PAL);
 
 // Global Variable Declarations

 
 GlobalVariable* gvar_array__str = new GlobalVariable(/*Module=*/*mod, 
 /*Type=*/ArrayTy_0,
 /*isConstant=*/true,
 /*Linkage=*/GlobalValue::PrivateLinkage,
 /*Initializer=*/0, // has initializer, specified below
 /*Name=*/".str");
 gvar_array__str->setAlignment(1);
 
 // Constant Definitions
 Constant *const_array_13 = ConstantDataArray::getString(mod->getContext(), "Answer is %d\x0A", true);
 ConstantInt* const_int32_14 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
 ConstantInt* const_int32_15 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("2"), 10));
 ConstantInt* const_int32_16 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("0"), 10));
 ConstantInt* const_int32_17 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("4"), 10));
 ConstantInt* const_int32_18 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("21"), 10));
 ConstantInt* const_int32_19 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("145"), 10));
 std::vector<Constant*> const_ptr_20_indices;
 const_ptr_20_indices.push_back(const_int32_16);
 const_ptr_20_indices.push_back(const_int32_16);
 Constant* const_ptr_20 = ConstantExpr::getGetElementPtr(gvar_array__str, const_ptr_20_indices);
 
 // Global Variable Definitions
 gvar_array__str->setInitializer(const_array_13);
 
 // Function Definitions
 
 // Function: _Z13some_functioni (func__Z13some_functioni)
 {
  Function::arg_iterator args = func__Z13some_functioni->arg_begin();
  Value* int32_input = args++;
  int32_input->setName("input");
  
  BasicBlock* label_21 = BasicBlock::Create(mod->getContext(), "",func__Z13some_functioni,0);
  
  // Block  (label_21)
  AllocaInst* ptr_22 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "", label_21);
  ptr_22->setAlignment(4);
  StoreInst* void_23 = new StoreInst(int32_input, ptr_22, false, label_21);
  void_23->setAlignment(4);
  LoadInst* int32_24 = new LoadInst(ptr_22, "", false, label_21);
  int32_24->setAlignment(4);
  BinaryOperator* int32_25 = BinaryOperator::Create(Instruction::Mul, int32_24, const_int32_15, "", label_21);
  ReturnInst::Create(mod->getContext(), int32_25, label_21);
  
 }
 
 // Function: main (func_main)
 {
  
  BasicBlock* label_27 = BasicBlock::Create(mod->getContext(), "",func_main,0);
  
  // Block  (label_27)
  AllocaInst* ptr_28 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "", label_27);
  ptr_28->setAlignment(4);
  AllocaInst* ptr_x = new AllocaInst(IntegerType::get(mod->getContext(), 32), "x", label_27);
  ptr_x->setAlignment(4);
  AllocaInst* ptr_fun = new AllocaInst(StructTy_class_anon, "fun", label_27);
  ptr_fun->setAlignment(4);
  AllocaInst* ptr_answer = new AllocaInst(IntegerType::get(mod->getContext(), 32), "answer", label_27);
  ptr_answer->setAlignment(4);
  AllocaInst* ptr_d = new AllocaInst(IntegerType::get(mod->getContext(), 32), "d", label_27);
  ptr_d->setAlignment(4);
  StoreInst* void_29 = new StoreInst(const_int32_16, ptr_28, false, label_27);
  StoreInst* void_30 = new StoreInst(const_int32_17, ptr_x, false, label_27);
  void_30->setAlignment(4);
  std::vector<Value*> ptr_31_indices;
  ptr_31_indices.push_back(const_int32_16);
  ptr_31_indices.push_back(const_int32_16);
  Instruction* ptr_31 = GetElementPtrInst::Create(ptr_fun, ptr_31_indices, "", label_27);
  LoadInst* int32_32 = new LoadInst(ptr_x, "", false, label_27);
  int32_32->setAlignment(4);
  StoreInst* void_33 = new StoreInst(int32_32, ptr_31, false, label_27);
  void_33->setAlignment(4);
  CallInst* int32_34 = CallInst::Create(func__Z13some_functioni, const_int32_18, "", label_27);
  int32_34->setCallingConv(CallingConv::C);
  int32_34->setTailCall(false);
  AttributeSet int32_34_PAL;
  int32_34->setAttributes(int32_34_PAL);
  
  StoreInst* void_35 = new StoreInst(int32_34, ptr_answer, false, label_27);
  void_35->setAlignment(4);
  std::vector<Value*> int32_36_params;
  int32_36_params.push_back(ptr_fun);
  int32_36_params.push_back(const_int32_19);
  CallInst* int32_36 = CallInst::Create(func__ZZ4mainENK3__0clEi, int32_36_params, "", label_27);
  int32_36->setCallingConv(CallingConv::C);
  int32_36->setTailCall(false);
  AttributeSet int32_36_PAL;
  int32_36->setAttributes(int32_36_PAL);
  
  StoreInst* void_37 = new StoreInst(int32_36, ptr_d, false, label_27);
  void_37->setAlignment(4);
  LoadInst* int32_38 = new LoadInst(ptr_answer, "", false, label_27);
  int32_38->setAlignment(4);
  std::vector<Value*> int32_39_params;
  int32_39_params.push_back(const_ptr_20);
  int32_39_params.push_back(int32_38);
  CallInst* int32_39 = CallInst::Create(func_printf, int32_39_params, "", label_27);
  int32_39->setCallingConv(CallingConv::C);
  int32_39->setTailCall(false);
  AttributeSet int32_39_PAL;
  int32_39->setAttributes(int32_39_PAL);
  
  ReturnInst::Create(mod->getContext(), const_int32_16, label_27);
  
 }
 
 // Function: _ZZ4mainENK3$_0clEi (func__ZZ4mainENK3__0clEi)
 {
  Function::arg_iterator args = func__ZZ4mainENK3__0clEi->arg_begin();
  Value* ptr_this = args++;
  ptr_this->setName("this");
  Value* int32_a = args++;
  int32_a->setName("a");
  
  BasicBlock* label_41 = BasicBlock::Create(mod->getContext(), "",func__ZZ4mainENK3__0clEi,0);
  
  // Block  (label_41)
  AllocaInst* ptr_42 = new AllocaInst(PointerTy_5, "", label_41);
  ptr_42->setAlignment(8);
  AllocaInst* ptr_43 = new AllocaInst(IntegerType::get(mod->getContext(), 32), "", label_41);
  ptr_43->setAlignment(4);
  StoreInst* void_44 = new StoreInst(ptr_this, ptr_42, false, label_41);
  void_44->setAlignment(8);
  StoreInst* void_45 = new StoreInst(int32_a, ptr_43, false, label_41);
  void_45->setAlignment(4);
  LoadInst* ptr_46 = new LoadInst(ptr_42, "", false, label_41);
  LoadInst* int32_47 = new LoadInst(ptr_43, "", false, label_41);
  int32_47->setAlignment(4);
  std::vector<Value*> ptr_48_indices;
  ptr_48_indices.push_back(const_int32_16);
  ptr_48_indices.push_back(const_int32_16);
  Instruction* ptr_48 = GetElementPtrInst::Create(ptr_46, ptr_48_indices, "", label_41);
  LoadInst* int32_49 = new LoadInst(ptr_48, "", false, label_41);
  int32_49->setAlignment(4);
  BinaryOperator* int32_50 = BinaryOperator::Create(Instruction::Add, int32_47, int32_49, "", label_41);
  ReturnInst::Create(mod->getContext(), int32_50, label_41);
  
 }
 
 return mod;
}
